#!/bin/bash

pip install -U ipywidgets
jupyter nbextension enable --py widgetsnbextension --sys-prefix

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

test -e test.png && rm test.png
